[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "breeze"
version = "0.0.1"
authors = [
    { name = "星灿长风v(StarWindv)", email = "starwindv.stv@gmail.com"}
]
license = { text = "BSD-3" }
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ariadne_py@git+https://github.com/CWind-Project/ariadne-py",
    "brich@git+https://github.com/CWind-Project/brich",
    "rich (>=15.0.0,<16.0.0)",
    "dulwich (>=1.2.15,<2.0.0)",
]

[project.scripts]
breeze = "breeze.cli:main"

[tool.setuptools.package-data]
breeze = [
    "assets/template/**/*",
    "assets/template/.gitignore",
]
